name: Tests
on:
  push:
    paths:
      - index.*
      - .github/workflows/**
      - action.yml

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - name: Install helmwave
        uses: helmwave/setup-action@v0.1.0
        with:
          version: '0.17.1'
      - run: helmwave --version
     
