name: Tests
on:
  push:
    paths:
      - index.*
      - .github/workflows/**
      - action.yml

jobs:
  external:
    runs-on: ubuntu-latest
    steps:
      - uses: helmwave/setup-action@v0.1.2
        name: Install helmwave
        with:
          version: '0.17.1'
      - run: helmwave --version
  
  internal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: ./
        name: Install helmwave
        with:
          version: '0.17.1'
        id: install
      - run: ${{ steps.install.outputs.path }} --version
      - run: helmwave --version

