name: Tests
on:
  push:
    paths:
      - index.*
      - .github/workflows/**
      - action.yml

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: npm run all
      - uses: actions/checkout@v2
      - run: |
          npm install
      - uses: ./
        name: Install helmwave
        with:
          version: '0.17.1'
      - run: helmwave --version


     
